baseURL = "https://www.leelanuevaconstitucion.cl"
languageCode = "es-cl"
title = "Lee la futura constituci√≥n"
paginate = 50

[params]
    BookSection = 'comisiones'
    BookSearch = true
    enableEmoji = true
    BookToc = false
